'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'このソース コードは xsd によって自動生成されました。Version=4.6.1055.0 です。
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://olp.yahooapis.jp/ydf/1.0"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0", IsNullable:=false)>  _
Partial Public Class YDF
    
    Private itemsField() As Object
    
    Private firstResultPositionField As Integer
    
    Private firstResultPositionFieldSpecified As Boolean
    
    Private totalResultsAvailableField As Integer
    
    Private totalResultsAvailableFieldSpecified As Boolean
    
    Private totalResultsReturnedField As Integer
    
    Private totalResultsReturnedFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Dictionary", GetType(DictionaryType)),  _
     System.Xml.Serialization.XmlElementAttribute("Feature", GetType(FeatureType)),  _
     System.Xml.Serialization.XmlElementAttribute("ResultInfo", GetType(ResultType))>  _
    Public Property Items() As Object()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property firstResultPosition() As Integer
        Get
            Return Me.firstResultPositionField
        End Get
        Set
            Me.firstResultPositionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property firstResultPositionSpecified() As Boolean
        Get
            Return Me.firstResultPositionFieldSpecified
        End Get
        Set
            Me.firstResultPositionFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property totalResultsAvailable() As Integer
        Get
            Return Me.totalResultsAvailableField
        End Get
        Set
            Me.totalResultsAvailableField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property totalResultsAvailableSpecified() As Boolean
        Get
            Return Me.totalResultsAvailableFieldSpecified
        End Get
        Set
            Me.totalResultsAvailableFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property totalResultsReturned() As Integer
        Get
            Return Me.totalResultsReturnedField
        End Get
        Set
            Me.totalResultsReturnedField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property totalResultsReturnedSpecified() As Boolean
        Get
            Return Me.totalResultsReturnedFieldSpecified
        End Get
        Set
            Me.totalResultsReturnedFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Partial Public Class DictionaryType
    
    Private itemField As System.Xml.XmlElement
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAnyElementAttribute()>  _
    Public Property Item() As System.Xml.XmlElement
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Partial Public Class FeatureType
    
    Private itemsField() As Object
    
    Private itemsElementNameField() As ItemsChoiceType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Category", GetType(String)),  _
     System.Xml.Serialization.XmlElementAttribute("Description", GetType(String)),  _
     System.Xml.Serialization.XmlElementAttribute("Geometry", GetType(GeometryType)),  _
     System.Xml.Serialization.XmlElementAttribute("Id", GetType(String)),  _
     System.Xml.Serialization.XmlElementAttribute("Name", GetType(String)),  _
     System.Xml.Serialization.XmlElementAttribute("Property", GetType(PropertyType)),  _
     System.Xml.Serialization.XmlElementAttribute("RouteInfo", GetType(RouteType)),  _
     System.Xml.Serialization.XmlElementAttribute("Style", GetType(StyleType)),  _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
    Public Property Items() As Object()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
     System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ItemsElementName() As ItemsChoiceType()
        Get
            Return Me.itemsElementNameField
        End Get
        Set
            Me.itemsElementNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Partial Public Class GeometryType
    
    Private idField As String
    
    Private targetField As String
    
    Private typeField As GeometryTypeType
    
    Private coordinatesField As String
    
    Private boundingBoxField As String
    
    Private compressField As String
    
    Private compressTypeField As String
    
    Private datumField As GeometryTypeDatum
    
    Private datumFieldSpecified As Boolean
    
    Private exteriorField As PolygonType
    
    Private interiorField As PolygonType
    
    Private radiusField As String
    
    Private geometryField() As GeometryType
    
    '''<remarks/>
    Public Property Id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Target() As String
        Get
            Return Me.targetField
        End Get
        Set
            Me.targetField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Type() As GeometryTypeType
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Coordinates() As String
        Get
            Return Me.coordinatesField
        End Get
        Set
            Me.coordinatesField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property BoundingBox() As String
        Get
            Return Me.boundingBoxField
        End Get
        Set
            Me.boundingBoxField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Compress() As String
        Get
            Return Me.compressField
        End Get
        Set
            Me.compressField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CompressType() As String
        Get
            Return Me.compressTypeField
        End Get
        Set
            Me.compressTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Datum() As GeometryTypeDatum
        Get
            Return Me.datumField
        End Get
        Set
            Me.datumField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property DatumSpecified() As Boolean
        Get
            Return Me.datumFieldSpecified
        End Get
        Set
            Me.datumFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Exterior() As PolygonType
        Get
            Return Me.exteriorField
        End Get
        Set
            Me.exteriorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Interior() As PolygonType
        Get
            Return Me.interiorField
        End Get
        Set
            Me.interiorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Radius() As String
        Get
            Return Me.radiusField
        End Get
        Set
            Me.radiusField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Geometry")>  _
    Public Property Geometry() As GeometryType()
        Get
            Return Me.geometryField
        End Get
        Set
            Me.geometryField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Public Enum GeometryTypeType
    
    '''<remarks/>
    point
    
    '''<remarks/>
    linestring
    
    '''<remarks/>
    polygon
    
    '''<remarks/>
    circle
    
    '''<remarks/>
    ellipse
    
    '''<remarks/>
    multigeometry
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Public Enum GeometryTypeDatum
    
    '''<remarks/>
    wgs
    
    '''<remarks/>
    tky
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Partial Public Class PolygonType
    
    Private coordinatesField As String
    
    '''<remarks/>
    Public Property Coordinates() As String
        Get
            Return Me.coordinatesField
        End Get
        Set
            Me.coordinatesField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Partial Public Class PropertyType
    
    Private itemsField() As System.Xml.XmlElement
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAnyElementAttribute()>  _
    Public Property Items() As System.Xml.XmlElement()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Partial Public Class RouteType
    
    Private edgeField() As EdgeType
    
    Private propertyField() As System.Xml.XmlElement
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Edge")>  _
    Public Property Edge() As EdgeType()
        Get
            Return Me.edgeField
        End Get
        Set
            Me.edgeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("", IsNullable:=false)>  _
    Public Property [Property]() As System.Xml.XmlElement()
        Get
            Return Me.propertyField
        End Get
        Set
            Me.propertyField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Partial Public Class EdgeType
    
    Private idField As String
    
    Private vertexField() As VertexType
    
    Private propertyField() As System.Xml.XmlElement
    
    '''<remarks/>
    Public Property Id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Vertex")>  _
    Public Property Vertex() As VertexType()
        Get
            Return Me.vertexField
        End Get
        Set
            Me.vertexField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("", IsNullable:=false)>  _
    Public Property [Property]() As System.Xml.XmlElement()
        Get
            Return Me.propertyField
        End Get
        Set
            Me.propertyField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Partial Public Class VertexType
    
    Private typeField As VertexTypeType
    
    Private propertyField() As System.Xml.XmlElement
    
    '''<remarks/>
    Public Property Type() As VertexTypeType
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("", IsNullable:=false)>  _
    Public Property [Property]() As System.Xml.XmlElement()
        Get
            Return Me.propertyField
        End Get
        Set
            Me.propertyField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Public Enum VertexTypeType
    
    '''<remarks/>
    Start
    
    '''<remarks/>
    [End]
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Partial Public Class StyleType
    
    Private idField As String
    
    Private targetField As String
    
    Private typeField As StyleTypeType
    
    Private imageField As String
    
    Private sizeField As String
    
    Private anchorField As String
    
    Private opacityField As Decimal
    
    Private opacityFieldSpecified As Boolean
    
    Private colorField As String
    
    Private startLineField As LineEndType
    
    Private startLineFieldSpecified As Boolean
    
    Private endLineField As LineEndType
    
    Private endLineFieldSpecified As Boolean
    
    '''<remarks/>
    Public Property Id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Target() As String
        Get
            Return Me.targetField
        End Get
        Set
            Me.targetField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Type() As StyleTypeType
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Image() As String
        Get
            Return Me.imageField
        End Get
        Set
            Me.imageField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Size() As String
        Get
            Return Me.sizeField
        End Get
        Set
            Me.sizeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Anchor() As String
        Get
            Return Me.anchorField
        End Get
        Set
            Me.anchorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Opacity() As Decimal
        Get
            Return Me.opacityField
        End Get
        Set
            Me.opacityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property OpacitySpecified() As Boolean
        Get
            Return Me.opacityFieldSpecified
        End Get
        Set
            Me.opacityFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property StartLine() As LineEndType
        Get
            Return Me.startLineField
        End Get
        Set
            Me.startLineField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property StartLineSpecified() As Boolean
        Get
            Return Me.startLineFieldSpecified
        End Get
        Set
            Me.startLineFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property EndLine() As LineEndType
        Get
            Return Me.endLineField
        End Get
        Set
            Me.endLineField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property EndLineSpecified() As Boolean
        Get
            Return Me.endLineFieldSpecified
        End Get
        Set
            Me.endLineFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Public Enum StyleTypeType
    
    '''<remarks/>
    icon
    
    '''<remarks/>
    line
    
    '''<remarks/>
    fill
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Public Enum LineEndType
    
    '''<remarks/>
    arrow
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0", IncludeInSchema:=false)>  _
Public Enum ItemsChoiceType
    
    '''<remarks/>
    Category
    
    '''<remarks/>
    Description
    
    '''<remarks/>
    Geometry
    
    '''<remarks/>
    Id
    
    '''<remarks/>
    Name
    
    '''<remarks/>
    [Property]
    
    '''<remarks/>
    RouteInfo
    
    '''<remarks/>
    Style
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://olp.yahooapis.jp/ydf/1.0")>  _
Partial Public Class ResultType
    
    Private countField As ULong
    
    Private totalField As ULong
    
    Private startField As ULong
    
    Private latencyField As Decimal
    
    Private statusField As ULong
    
    Private descriptionField As String
    
    Private copyrightField As String
    
    '''<remarks/>
    Public Property Count() As ULong
        Get
            Return Me.countField
        End Get
        Set
            Me.countField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Total() As ULong
        Get
            Return Me.totalField
        End Get
        Set
            Me.totalField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Start() As ULong
        Get
            Return Me.startField
        End Get
        Set
            Me.startField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Latency() As Decimal
        Get
            Return Me.latencyField
        End Get
        Set
            Me.latencyField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Status() As ULong
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Description() As String
        Get
            Return Me.descriptionField
        End Get
        Set
            Me.descriptionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Copyright() As String
        Get
            Return Me.copyrightField
        End Get
        Set
            Me.copyrightField = value
        End Set
    End Property
End Class
